name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    env:
      NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
      IMAGE_TAG: ${{ secrets.REGISTRY }}/atpack-mirror:latest
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - run: |
        echo '{ "insecure-registries" : ["${{ secrets.REGISTRY }}"] }' > temp.json && sudo mv temp.json /etc/docker/daemon.json
        sudo systemctl restart docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
        buildkitd-config-inline: |
          [registry."${{ secrets.REGISTRY }}"]
            http = true
            insecure = true
    - name: Build and push
      id: docker
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE_TAG }}
    - name: Capture Digest
      run: |
        # Capture the digest
        DIGEST=$(docker buildx imagetools inspect ${{ env.IMAGE_TAG }} | grep Digest | awk '{print $2}')
        echo $DIGEST
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV
    - name: Setup `nomad`
      uses: hashicorp/setup-nomad@main
      with:
        version: 1.9.1
    - name: Deploy to nomad
      env:
        LOG_LEVEL: info
        DOMAIN: atpack.microzig.tech
        IMAGE: ${{ env.IMAGE_TAG }}@${{ env.DIGEST }}
        LOKI_URL: ${{ secrets.LOKI_URL }}
      run: nomad job run <(./deploy.sh)
